# @package _global_

hydra:
  run:
    dir: '/Users/ctang/Library/CloudStorage/OneDrive-Personal/CODE/Wind_reu/'

# Directories
dir:
  working: /Users/ctang/Microsoft_OneDrive/OneDrive/CODE/Wind_reu
  data: ./dataset
  plot: ./plot
  obs: /Users/ctang/climate/GLOBALDATA/OBSDATA/

data:
  mf_station: './local_data/MF/mf.station.csv'
  mf_all: './local_data/MF/ff.dd.hourly.mf.2000-2020.csv'

job:
  voronoi: 0
  missing_MF: 0
  multi_year_mean: 0
  climatology: 0
  MF_station_clustering: 1

figure:
  reunion_voronoi_mf: ./plot/voronoi_reu_mf.png
  reunion_voronoi_mf_alt: ./plot/voronoi_reu_mf_alt.png
  reunion_voronoi_mf_speed_10m: ./plot/voronoi_reu_mf_speed_10m.png
  reunion_missing_mf: ./plot/missing_mf
  station_mean_ff_10m: ./plot/station_mean_ff_10m.png
  station_std_ff_10m: ./plot/station_std_ff_10m.png
  DBSCAN_cluster_climatology_MF_ff_10m: ./plot/DBSCAN_cluster_climatology_MF_ff_10m.png

param:
  HUB_HEIGHT: 100

input:
  ssr_clusters: ./dataset/classifications__2_to_20_Cl.csv








