# @package _global_

hydra:
  run:
    dir: '/Users/ctang/Library/CloudStorage/OneDrive-Personal/CODE/Wind_reu/'

# Directories
dir:
  working: /Users/ctang/Microsoft_OneDrive/OneDrive/CODE/Wind_reu
  data: ./dataset
  plot: ./plot
  obs: /Users/ctang/climate/GLOBALDATA/OBSDATA/

data:
  mf_station: './local_data/MF/mf.station.csv'
  mf_all: './local_data/MF/ff.dd.hourly.mf.2000-2020.csv'

job:
  voronoi: 0
  missing_MF: 0
  climatology: 1

figure:
    reunion_voronoi_mf_alt: /Users/ctang/Microsoft_OneDrive/OneDrive/CODE/Wind_reu/plot/voronoi_reu_mf_alt.png
    reunion_voronoi_mf_speed: /Users/ctang/Microsoft_OneDrive/OneDrive/CODE/Wind_reu/plot/voronoi_reu_mf_speed.png
    reunion_missing_mf: /Users/ctang/Microsoft_OneDrive/OneDrive/CODE/Wind_reu/plot/missing_mf

param:
  HUB_HEIGHT: 100

input:
  ssr_clusters: ./dataset/classifications__2_to_20_Cl.csv








