# @package _global_

hydra:
  run:
    dir: '/Users/ctang/Library/CloudStorage/OneDrive-Personal/CODE/Wind_reu/'

# Directories
dir:
  working: /Users/ctang/Microsoft_OneDrive/OneDrive/CODE/Wind_reu
  data: /Users/ctang/Microsoft_OneDrive/OneDrive/CODE/Wind_reu/dataset
  local_data: /Users/ctang/Microsoft_OneDrive/OneDrive/CODE/Wind_reu/local_data
  plot: /Users/ctang/Microsoft_OneDrive/OneDrive/CODE/Wind_reu/plot
  obs: /Users/ctang/climate/GLOBALDATA/OBSDATA/

data:
  mf: 'mf.csv'
  mf_station: 'mf.station.csv'

job:
  data: 0
  # used only in DATA
  voronoi: 1

figure:
    reunion_voronoi_mf: /Users/ctang/Microsoft_OneDrive/OneDrive/CODE/Wind_reu/plot/voronoi_reu_mf.png

param:
  sarah_e_end_year: 2016
  HUB_HEIGHT: 100

input:
  ssr_clusters: ./dataset/classifications__2_to_20_Cl.csv


plot:
  output_param: 0
  wind_change_min: -2
  wind_change_max: 2
  cyclone_class: 'cyclone_class.csv'

output:
  plot:
    mf_data_missing: 'missing_check_mf.png'







